// Generated by Wrangler by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	FRONTEND_URL: string;
	BACKEND_URL: string;
	JWT_SECRET: string;
	BUCKET: R2Bucket;
	DB: D1Database;
}
