import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Header from "./_components/Header";
import AuthProvider from "@/provider/AuthProvider";
import Loading from "@/provider/LoadingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#00BC7D" />
      </head>
      <body
        className={`font-amd antialiased bg-zinc-50 text-black h-screen`}
      >
        <AuthProvider>
          <Loading>
            <Header />
            <div>
              {children}
            </div>
          </Loading>
        </AuthProvider>
      </body>
    </html>
  );
}
